### ISSUE TITLE
Multiple GPU with Xrog

### ISSUE THREAD

**Issue by luqasz** [pavolelsig/L-G_helper#1]
Hi.

I've watched your guides on YT. Difference between our setups is that I am using wayland, you are using Xorg. Problem is that I can't use Xorg because desktop [doesn't launch](https://pastebin.com/0RJttTks) at all when reserving AMD GPU with `vfio-pci.ids`. Only wayland works. Although looking glass client launches and I can do most stuff BUT, input capturing is not locking e.g. ALT+TAB and scroll wheel is always scrolling in one direction. Playing games without scroll is a PITA. 

How did you manage to use Xorg with reserved GPU ?

I am using ubuntu 20.04.

**Comment by pavolelsig** [comment]
If the main issue you're having is your mouse, just pass through the mouse to the VM. I don't think using xorg will fix the scrolling issue.

**Comment by luqasz** [comment]
I had to export `SDL_VIDEODRIVER=x11` then launch lg. Scrolling is fixed but ALT+TAB still is not captured. LG doesn't support wayland 100%. Switching to X11 will resolve problems / LG will have to support wayland 100%.

**Comment by pavolelsig** [comment]
As far as xorg goes, do you have issues before you bind the secondary GPU to vfio. If that's the case, try booting with nomodeset parameter in grub. And then run the script. Afterwards, once it's bound to vfio, I've never had issues.

**Comment by luqasz** [comment]
Eh... `nomodeset` results in non native resolution and I can not even change it. 
@pavolelsig when you have additional GPU passed through, do you have internal GPU (in CPU) set as primary in BIOS ?

**Comment by pavolelsig** [comment]
I normally use the iGPU for the host and set it as primary in BIOS. Sometimes I do have issues when I first boot into a fresh install and the GUI won't start. Nomodeset lets the GUI start. Afterwards I bind the secondary GPU to vfio. After that everything should just work without having to use nomodeset.

**Comment by luqasz** [comment]
I think I know what the problem is. My BIOS uses added GPU card as primary even though I've set to use internal GPU as primary. That is why I have problems down the road with xorg. I will have to solve BIOS problem first I think.

**Comment by luqasz** [comment]
Upgrading my BIOS did not solve my problem. Motherboard still uses added GPU as primary....
